"""empty message

Revision ID: 21a3810b9ce0
Revises: a09bc0ccfd85
Create Date: 2025-05-16 20:50:50.992689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21a3810b9ce0'
down_revision = 'a09bc0ccfd85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=True),
    sa.Column('file_path', sa.String(length=300), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('salary', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('education', sa.String(length=100), nullable=True),
    sa.Column('graduation_date', sa.Date(), nullable=True),
    sa.Column('school', sa.String(length=200), nullable=True),
    sa.Column('expected_company', sa.String(length=200), nullable=True),
    sa.Column('career_goal', sa.String(length=200), nullable=True),
    sa.Column('self_description', sa.Text(), nullable=True),
    sa.Column('internship_experience', sa.Text(), nullable=True),
    sa.Column('gpa', sa.String(length=10), nullable=True),
    sa.Column('coding_c', sa.Boolean(), nullable=True),
    sa.Column('coding_cpp', sa.Boolean(), nullable=True),
    sa.Column('coding_java', sa.Boolean(), nullable=True),
    sa.Column('coding_sql', sa.Boolean(), nullable=True),
    sa.Column('coding_python', sa.Boolean(), nullable=True),
    sa.Column('working_experience', sa.Integer(), nullable=True),
    sa.Column('communication_skill', sa.Integer(), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('viz_share',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('shared_to_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shared_to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('owner_id', 'shared_to_user_id')
    )
    op.create_table('shared_with',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('shared_to_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['shared_to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('document_id', 'shared_to_user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_with')
    op.drop_table('viz_share')
    op.drop_table('profiles')
    op.drop_table('password_reset_tokens')
    op.drop_table('job_history')
    op.drop_table('documents')
    op.drop_table('users')
    # ### end Alembic commands ###
