"""Add VizShare table

Revision ID: 2d86b45dbbef
Revises: c45377944973
Create Date: 2025-05-07 12:19:03.815770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d86b45dbbef'
down_revision = 'c45377944973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viz_share',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('shared_to_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shared_to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('owner_id', 'shared_to_user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viz_share')
    # ### end Alembic commands ###
