"""empty message

Revision ID: b74172130896
Revises: 955fe0f5cd24
Create Date: 2025-05-12 13:28:52.180468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b74172130896'
down_revision = '955fe0f5cd24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gpa', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('coding_c', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('coding_cpp', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('coding_java', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('coding_sql', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('coding_python', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('working_experience', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('communication_skill', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('communication_skill')
        batch_op.drop_column('working_experience')
        batch_op.drop_column('coding_python')
        batch_op.drop_column('coding_sql')
        batch_op.drop_column('coding_java')
        batch_op.drop_column('coding_cpp')
        batch_op.drop_column('coding_c')
        batch_op.drop_column('gpa')

    # ### end Alembic commands ###
