"""Add SharedWith table

Revision ID: c45377944973
Revises: 
Create Date: 2025-05-07 11:35:56.779807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c45377944973'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_with',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('shared_to_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['shared_to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('document_id', 'shared_to_user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_with')
    # ### end Alembic commands ###
